### PR TITLE
Show command made more dynamic and several new commands implemented.

### PR DESCRIPTION
**Pull request by nymx**
The show command can be expanded by creating new functions that start with 'show_', similarly to 'command_'. A 'clear' screen command and a print 'banner' command were also implemented.

### CODE REVIEW

**Comment by nymx** [comment]
@lucyoa Okay, I think that this should work.

**Comment by lucyoa** [comment]
@nymx Adding new command requires:
- implementing command (you already done this)
- adding command to completer
- adding command to test suite

Could you adapt PR?

**Comment by nymx** [comment]
@lucyoa I'm not sure what PR means, but I'll modify the 'complete_show' function to find commands from the global list of functions.

**Comment by nymx** [comment]
@lucyoa I implemented auto-completing without a predefined list of commands. I'm going to look at the test suite to figure out how I can do that there, too.

**Comment by lucyoa** [comment]
@nymx Why there is another interpreter.py file outside routersploit?

**Comment by nymx** [comment]
@lucyoa That is a very good question. I don't actually know, so I'm going to fix that now.

**Pull request closed without merging**
